#Do not record received requests. Typically, needed during load testing to avoid JVM heap exhaustion.
wiremock:
    requestJournalDisabled: true
    verboseLoggingEnabled: true

server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: test01
    key-store-type: PKCS12
    key-alias: https
    key-password: test01
  port: 8443

container:
  jar:
    root: /container
  file:
    root: ${java.io.tmpdir}/mappings
